server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/switch_docs?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
    username: root
    password: root
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      pool-name: HikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      validation-timeout: 5000
      leak-detection-threshold: 15000

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: org.ygsq.wk.mapper

logging:
  level:
    root: INFO
    org.yjsq.wk: DEBUG
#    org.mybatis.spring.SqlSessionFactoryBean: DEBUG
#    org.apache.ibatis: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    db:
      enabled: true

system:
  login:
    cache: 12